### ISSUE TITLE
SteamVR icon overlaps with drop down menu icon

### ISSUE THREAD

**Issue by realredun** [cyberwitch/hidename#2]
The SteamVR icon overlaps with the drop down menu. I encountered this issue running the latest version of windows 10 and steam. Below is an image demonstrating the problem as well as another image showing what the layout looks like in vanilla steam:

![theissue](https://user-images.githubusercontent.com/35180850/34645221-31a57b50-f30d-11e7-8f7c-5f53ea0a6ce7.png)

![desiredlayout](https://user-images.githubusercontent.com/35180850/34645246-2b4063aa-f30e-11e7-81a0-0e718d2b1aae.png)

**Comment by cyberwitch** [comment]
Hi @realredun,

Thanks for letting me know!  Unfortunately, I don't have VR equipment so I don't think I can get the VR icon to show up to test it myself.  But I updated my skin for the latest version of Steam, and tried to adjust the placement of the profile icon so it sits to the left of the VR icon.

If you would give it a try, and let me know if it works (or provide screenshots if it doesn't) I'd appreciate the help!  Here's the branch with the proposed fix: https://github.com/cyberwitch/hidename/tree/fix-vr

**Comment by realredun** [comment]
Just tested it and it works flawlessly! Thanks for the quick response! I was contemplating making a new steam account and using family sharing with my old account but your solution is so much cleaner and more effective. Thanks for saving my steam account from early retirement. If I encounter any other issues down the road I'll be sure to report them here.

**Comment by cyberwitch** [comment]
Awesome, thanks!  I'm glad it worked.  I'll merge that branch, and please do let me know if you find any other issues.  If I have time I might take another try at hiding the name in other places - I'd actually forgotten about this project.
